### ISSUE TITLE
A bit confused

### ISSUE THREAD

**Issue by ElieeCh** [scaljeri/agario-driver#1]
So what is it supposed to do ? I read the readme but still couldn't really understand

**Comment by scaljeri** [comment]
I can imagine that : )

Its a work in progress. The initial idea is to have something that can play agario for you and collect points for you. Although that thought hasn't gone away, I'm now more focussed on writing a good bot (the other project) all based on image image progressing (analysing the pixels of the agario `<canvas>`). This project will control the browser and provide tools (shared folder) for writing a bot.

**Comment by ElieeCh** [comment]
Nice, looks very interesting. I'll keep an eye here and follow you throw every update :) (if you don't mind).

**Comment by scaljeri** [comment]
no problem :)
